// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpREEArzxqUZwk7Txe_mNlyfYyJCAP_90',
    appId: '1:333975810014:web:5dfe3e6966261bafa6f74f',
    messagingSenderId: '333975810014',
    projectId: 'messengerapp-710e1',
    authDomain: 'messengerapp-710e1.firebaseapp.com',
    databaseURL: 'https://messengerapp-710e1-default-rtdb.firebaseio.com',
    storageBucket: 'messengerapp-710e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBivytCm_IFBZEXEh-qAnHf6Ype8DM2Yfs',
    appId: '1:333975810014:android:86cd4faf940e8917a6f74f',
    messagingSenderId: '333975810014',
    projectId: 'messengerapp-710e1',
    databaseURL: 'https://messengerapp-710e1-default-rtdb.firebaseio.com',
    storageBucket: 'messengerapp-710e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIENuKBrDkawRVlpn88YJJOFRuZx_eCl8',
    appId: '1:333975810014:ios:6b696f2cf4b378faa6f74f',
    messagingSenderId: '333975810014',
    projectId: 'messengerapp-710e1',
    databaseURL: 'https://messengerapp-710e1-default-rtdb.firebaseio.com',
    storageBucket: 'messengerapp-710e1.appspot.com',
    iosClientId: '333975810014-v42aun3250di7j4ce7hk26bidgots246.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIENuKBrDkawRVlpn88YJJOFRuZx_eCl8',
    appId: '1:333975810014:ios:6b696f2cf4b378faa6f74f',
    messagingSenderId: '333975810014',
    projectId: 'messengerapp-710e1',
    databaseURL: 'https://messengerapp-710e1-default-rtdb.firebaseio.com',
    storageBucket: 'messengerapp-710e1.appspot.com',
    iosClientId: '333975810014-v42aun3250di7j4ce7hk26bidgots246.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );
}
